apiVersion: v1
kind: Namespace
metadata:
  name: artifactory-oss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-oss
  namespace: artifactory-oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory-oss
  template:
    metadata:
      labels:
        app: artifactory-oss
    spec:
      containers:
      - name: artifactory-oss
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        ports:
        - containerPort: 8081
          name: jfrog-http
        - containerPort: 8082
          name: jfrog-https
        volumeMounts:
          - name: artifactory-oss
            mountPath: /var/artifactory-oss
      volumes:
        - name: artifactory-oss
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-oss
  namespace: artifactory-oss
spec:
  type: NodePort
  selector:
    app: artifactory-oss
  ports:
    - name: jfrog-http
      port: 8081
      targetPort: 8081
      nodePort: 30801
    - name: jfrog-https
      port: 8082
      targetPort: 8082
      nodePort: 30802
