apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-pro
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory-pro
  template:
    metadata:
      labels:
        app: artifactory-pro
    spec:
      containers:
      - name: artifactory-pro
        image: docker.bintray.io/jfrog/artifactory-pro:latest
        ports:
        - containerPort: 8081
          name: jfrog-http
        - containerPort: 8082
          name: jfrog-router
        volumeMounts:
          - name: artifactory-pro
            mountPath: /var/artifactory-pro
      volumes:
        - name: artifactory-pro
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-pro
  namespace: artifactory
spec:
  type: NodePort
  selector:
    app: artifactory-pro
  ports:
    - name: jfrog-http
      port: 8081
      targetPort: 8081
      nodePort: 30801
    - name: jfrog-router
      port: 8082
      targetPort: 8082
      nodePort: 30802
