apiVersion: v1
kind: Namespace
metadata:
  name: bloody-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: bloody-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        privileged: true
        fsGroup: 1000
      containers:
      - name: jenkins
        image: odavid/my-bloody-jenkins
        env:
        - name: JENKINS_ENV_CONFIG_YML_URL
          value: "file:///var/jenkins_home/config.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
          - mountPath: /usr/bin/docker
            name: docker-executable
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
        - name: docker-executable
          hostPath:
            path:/usr/bin/docker
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: bloody-jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30800
      targetPort: 8080
  selector:
    app: jenkins
