credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "tomer"
          password: "{AQAAABAAAAAQ2r06vMHstRcf4kFx7R/msaj/zuaulD2C+sER8wVB8mk=}"
          scope: GLOBAL
          username: "tomer"
      - usernamePassword:
          id: "docker-credentials"
          password: "{AQAAABAAAAAgJtVrinZCNgZKthuOOR2olJYt20uczpBRN1jTNJduGyT3uP2nN59QZol+vQg0soxX}"
          scope: GLOBAL
          username: "sec911"
      - usernamePassword:
          id: "github-cred"
          password: "{AQAAABAAAAAgkRg5g6rB9mvAOeKd/3CWGUU9uomaIORJPFLWDMfGzhkkuSJreOWX+CRlpuSR1z/Y}"
          scope: GLOBAL
          username: "rfmsec"
jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Overall/Administer:tomer"
      - "Overall/Read:authenticated"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  - "jenkins.security.ResourceDomainRecommendation"
  - "jenkins.security.s2m.MasterKillSwitchWarning"
  mode: NORMAL
  noUsageStatistics: true
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "tomer"
        name: "Tomer"
        - mailer:
            emailAddress: "e@mail.com"