credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "tomer"
          password: "Aa123456"
          scope: GLOBAL
          username: "tomer"
jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Overall/Administer:tomer"
      - "Overall/Read:authenticated"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
  disabledAdministrativeMonitors:
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  - "jenkins.security.ResourceDomainRecommendation"
  - "jenkins.security.s2m.MasterKillSwitchWarning"
  noUsageStatistics: true
  numExecutors: 2
  quietPeriod: 3
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "tomer"
        password: "1234"
  slaveAgentPort: 50000 
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  artifactoryBuilder:
    artifactoryServers:
    - artifactoryUrl: "http://192.168.99.100:30802/artifactory"
      bypassProxy: false
      connectionRetry: 3
      deployerCredentialsConfig:
        credentialsId: "tomer"
        overridingCredentials: false
        password: "{AQAAABAAAAAQidEUzw5YwSyvck5zq4JEC9qoaAXcXusuoBAjzR2v2tU=}"
        username: "****"
      deploymentThreads: 3
      serverId: "Art01"
      timeout: 300
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQVvi3TcaLfKi1J1stH1R64tlXSVOVg1cKgVchyM5ABsw=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: true
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAAAQ6AEZQXU3sAmG/2b3mU5kl7Hqlk/3Kk2b2FbV1SLrYGw=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://192.168.99.100:30800/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  imageTagParameterConfiguration:
    defaultRegistry: "https://registry-1.docker.io"
    defaultTagOrdering: NATURAL
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://192.168.99.100:30800/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
tool:
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"
jobs:
  - script: >
      pipelineJob("GitHub_MiniServer_pipe") {
          description()
          keepDependencies(false)
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url("https://github.com/rfmsec/MiniServer.git")
                          }
                          branch("*")
                      }
                  }
                  scriptPath("Jenkinsfile")
              }
          }
          triggers {
              githubPush()
          }
          disabled(false)
      }
  - script: >
      pipelineJob("Deploy_Artifacts") {
          description()
          properties {
            pipelineTriggers {
              triggers {
                GenericTrigger {
                  genericVariables {
                    genericVariable {
                      key("ARTIFACT_NAME")
                      value("\$.artifactory.webhook.data.name")
                    }
                    genericVariable {
                      key("EVENT_NAME")
                      value("\$.artifactory.webhook.event")
                    }
                  }
                  causeString("Triggered on \$ARTIFACT_NAME")
                  regexpFilterText("\$EVENT_NAME-\$ARTIFACT_NAME")
                  regexpFilterExpression("storage\\.afterCreate-SuperPackage")
                  printContributedVariables(true)
                }     
              }
            }
          }
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url("https://github.com/rfmsec/MiniServer.git")
                          }
                          branch("*")
                      }
                  }
                  scriptPath("Jenkinsfile2")
              }
          }
          disabled(false)
      }