credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "tomer"
          password: "{AQAAABAAAAAQ2r06vMHstRcf4kFx7R/msaj/zuaulD2C+sER8wVB8mk=}"
          scope: GLOBAL
          username: "tomer"
      - usernamePassword:
          id: "docker-credentials"
          password: "{AQAAABAAAAAgJtVrinZCNgZKthuOOR2olJYt20uczpBRN1jTNJduGyT3uP2nN59QZol+vQg0soxX}"
          scope: GLOBAL
          username: "sec911"
      - usernamePassword:
          id: "github-cred"
          password: "{AQAAABAAAAAgkRg5g6rB9mvAOeKd/3CWGUU9uomaIORJPFLWDMfGzhkkuSJreOWX+CRlpuSR1z/Y}"
          scope: GLOBAL
          username: "rfmsec"

jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Overall/Administer:tomer"
      - "Overall/Read:authenticated"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  - "jenkins.security.ResourceDomainRecommendation"
  - "jenkins.security.s2m.MasterKillSwitchWarning"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "tomer"
        name: "Tomer"
        properties:
        - "apiToken"
        - favoriting:
            autofavoriteEnabled: true
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "user"
        - samlCustomProperty:
        - "slack"
        - "timezone"
        - "loginDetailsProperty"
        - mailer:
            emailAddress: "e@mail.com"
  
unclassified:
  artifactoryBuilder:
    artifactoryServers:
    - artifactoryUrl: "http://192.168.99.100:30802/artifactory"
      bypassProxy: false
      connectionRetry: 3
      deployerCredentialsConfig:
        credentialsId: "tomer"
        overridingCredentials: false
        password: "{AQAAABAAAAAQidEUzw5YwSyvck5zq4JEC9qoaAXcXusuoBAjzR2v2tU=}"
        username: "****"
      deploymentThreads: 3
      serverId: "Art01"
      timeout: 300
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQVvi3TcaLfKi1J1stH1R64tlXSVOVg1cKgVchyM5ABsw=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: true
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://192.168.99.100:30800/"
  pollSCM:
    pollingThreadCount: 10